import { DefaultErrorOptions } from '../clients/types/CommonTypes';

export enum ErrorCodes {
	HILAN_CREDENTIALS_EXPIRED = 1000,
	HILAN_CREDENTIALS_WRONG = 1001,
	HILAN_CREDENTIALS_MISSING = 1002,
	HILAN_FORMAUTOMATION = 1010,
	HILAN_ILLEGALARGUMENTS = 1020,
	HILAN_SCRAPING = 1030,
	HILAN_UNSUPPORTED_CONFIG = 1040,

	WEBTIME_CREDENTIALS_EXPIRED = 1100,
	WEBTIME_CREDENTIALS_WRONG = 1101,
	WEBTIME_CREDENTIALS_MISSING = 1102,
	WEBTIME_FORMAUTOMATION = 1110,
	WEBTIME_ILLEGALARGUMENTS = 1120,
	WEBTIME_SCRAPING = 1130,
	WEBTIME_UNSUPPORTED_CONFIG = 1140,

	GENERAL_UNSUPPORTED_TARGET = 2000,
	GENERAL_FORMAUTOMATION = 2010,
	GENERAL_ILLEGALARGUMENT = 2020,
	GENERAL_SCRAPING = 2030,
}

export class ErrorWithCode extends Error {
	errorCode: ErrorCodes;
	constructor({ message, errorCode }: DefaultErrorOptions) {
		super(message);
		this.errorCode = errorCode;
	}
}
